/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IMarsbaseSink } from "./IMarsbaseSink";
export type { IMarsbaseTreasury } from "./IMarsbaseTreasury";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { MarsbaseSwapMock } from "./MarsbaseSwapMock";
