/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IMarsbaseBestBid {
  export type BBOfferParamsStruct = {
    tokenAlice: PromiseOrValue<string>;
    amountAlice: PromiseOrValue<BigNumberish>;
    tokensBob: PromiseOrValue<string>[];
    feeAlice: PromiseOrValue<BigNumberish>;
    feeBob: PromiseOrValue<BigNumberish>;
  };

  export type BBOfferParamsStructOutput = [
    string,
    BigNumber,
    string[],
    BigNumber,
    BigNumber
  ] & {
    tokenAlice: string;
    amountAlice: BigNumber;
    tokensBob: string[];
    feeAlice: BigNumber;
    feeBob: BigNumber;
  };

  export type BBOfferStruct = {
    active: PromiseOrValue<boolean>;
    id: PromiseOrValue<BigNumberish>;
    aliceAddress: PromiseOrValue<string>;
    params: IMarsbaseBestBid.BBOfferParamsStruct;
    totalBidsCount: PromiseOrValue<BigNumberish>;
    activeBidsCount: PromiseOrValue<BigNumberish>;
  };

  export type BBOfferStructOutput = [
    boolean,
    BigNumber,
    string,
    IMarsbaseBestBid.BBOfferParamsStructOutput,
    BigNumber,
    BigNumber
  ] & {
    active: boolean;
    id: BigNumber;
    aliceAddress: string;
    params: IMarsbaseBestBid.BBOfferParamsStructOutput;
    totalBidsCount: BigNumber;
    activeBidsCount: BigNumber;
  };

  export type BBBidStruct = {
    offerId: PromiseOrValue<BigNumberish>;
    bidIdx: PromiseOrValue<BigNumberish>;
    bobAddress: PromiseOrValue<string>;
    tokenBob: PromiseOrValue<string>;
    amountBob: PromiseOrValue<BigNumberish>;
  };

  export type BBBidStructOutput = [
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber
  ] & {
    offerId: BigNumber;
    bidIdx: BigNumber;
    bobAddress: string;
    tokenBob: string;
    amountBob: BigNumber;
  };
}

export interface IMarsbaseBestBidInterface extends utils.Interface {
  functions: {
    "acceptBid(uint256,uint256)": FunctionFragment;
    "cancelBid(uint256,uint256)": FunctionFragment;
    "cancelOffer(uint256)": FunctionFragment;
    "createBid(uint256,address,uint256)": FunctionFragment;
    "createOffer((address,uint256,address[],uint256,uint256))": FunctionFragment;
    "getActiveOffers()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptBid"
      | "acceptBid(uint256,uint256)"
      | "cancelBid"
      | "cancelBid(uint256,uint256)"
      | "cancelOffer"
      | "cancelOffer(uint256)"
      | "createBid"
      | "createBid(uint256,address,uint256)"
      | "createOffer"
      | "createOffer((address,uint256,address[],uint256,uint256))"
      | "getActiveOffers"
      | "getActiveOffers()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptBid(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createBid",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createBid(uint256,address,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createOffer",
    values: [IMarsbaseBestBid.BBOfferParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createOffer((address,uint256,address[],uint256,uint256))",
    values: [IMarsbaseBestBid.BBOfferParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOffers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOffers()",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptBid(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBid(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBid(uint256,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOffer((address,uint256,address[],uint256,uint256))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOffers()",
    data: BytesLike
  ): Result;

  events: {
    "BidAccepted(uint256,address,uint256,uint256,uint256,uint256,tuple,tuple)": EventFragment;
    "BidCancelled(uint256,address,address,uint8,uint256,bytes32,tuple)": EventFragment;
    "BidCreated(uint256,address,address,uint256,bytes32,tuple)": EventFragment;
    "OfferClosed(uint256,address,uint8,tuple)": EventFragment;
    "OfferCreated(uint256,address,address,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BidAccepted"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BidAccepted(uint256,address,uint256,uint256,uint256,uint256,tuple,tuple)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCancelled"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BidCancelled(uint256,address,address,uint8,uint256,bytes32,tuple)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "BidCreated(uint256,address,address,uint256,bytes32,tuple)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferClosed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OfferClosed(uint256,address,uint8,tuple)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OfferCreated(uint256,address,address,tuple)"
  ): EventFragment;
}

export interface BidAcceptedEventObject {
  id: BigNumber;
  aliceAddress: string;
  aliceReceivedTotal: BigNumber;
  aliceFeeTotal: BigNumber;
  bobReceivedTotal: BigNumber;
  bobFeeTotal: BigNumber;
  offer: IMarsbaseBestBid.BBOfferStructOutput;
  bid: IMarsbaseBestBid.BBBidStructOutput;
}
export type BidAcceptedEvent = TypedEvent<
  [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IMarsbaseBestBid.BBOfferStructOutput,
    IMarsbaseBestBid.BBBidStructOutput
  ],
  BidAcceptedEventObject
>;

export type BidAcceptedEventFilter = TypedEventFilter<BidAcceptedEvent>;

export interface BidCancelledEventObject {
  offerId: BigNumber;
  bobAddress: string;
  tokenBob: string;
  reason: number;
  bidIdx: BigNumber;
  bidId: string;
  bid: IMarsbaseBestBid.BBBidStructOutput;
}
export type BidCancelledEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    number,
    BigNumber,
    string,
    IMarsbaseBestBid.BBBidStructOutput
  ],
  BidCancelledEventObject
>;

export type BidCancelledEventFilter = TypedEventFilter<BidCancelledEvent>;

export interface BidCreatedEventObject {
  offerId: BigNumber;
  bobAddress: string;
  tokenBob: string;
  bidIdx: BigNumber;
  bidId: string;
  bid: IMarsbaseBestBid.BBBidStructOutput;
}
export type BidCreatedEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    IMarsbaseBestBid.BBBidStructOutput
  ],
  BidCreatedEventObject
>;

export type BidCreatedEventFilter = TypedEventFilter<BidCreatedEvent>;

export interface OfferClosedEventObject {
  id: BigNumber;
  aliceAddress: string;
  reason: number;
  offer: IMarsbaseBestBid.BBOfferStructOutput;
}
export type OfferClosedEvent = TypedEvent<
  [BigNumber, string, number, IMarsbaseBestBid.BBOfferStructOutput],
  OfferClosedEventObject
>;

export type OfferClosedEventFilter = TypedEventFilter<OfferClosedEvent>;

export interface OfferCreatedEventObject {
  id: BigNumber;
  aliceAddress: string;
  tokenAlice: string;
  params: IMarsbaseBestBid.BBOfferParamsStructOutput;
}
export type OfferCreatedEvent = TypedEvent<
  [BigNumber, string, string, IMarsbaseBestBid.BBOfferParamsStructOutput],
  OfferCreatedEventObject
>;

export type OfferCreatedEventFilter = TypedEventFilter<OfferCreatedEvent>;

export interface IMarsbaseBestBid extends BaseContract {
  contractName: "IMarsbaseBestBid";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMarsbaseBestBidInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "acceptBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "cancelBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "cancelOffer(uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createBid(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "createBid(uint256,address,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createOffer(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "createOffer((address,uint256,address[],uint256,uint256))"(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getActiveOffers(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "getActiveOffers()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptBid(
    offerId: PromiseOrValue<BigNumberish>,
    bidIdx: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "acceptBid(uint256,uint256)"(
    offerId: PromiseOrValue<BigNumberish>,
    bidIdx: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelBid(
    offerId: PromiseOrValue<BigNumberish>,
    bidIdx: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "cancelBid(uint256,uint256)"(
    offerId: PromiseOrValue<BigNumberish>,
    bidIdx: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelOffer(
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "cancelOffer(uint256)"(
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createBid(
    offerId: PromiseOrValue<BigNumberish>,
    tokenBob: PromiseOrValue<string>,
    amountBob: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "createBid(uint256,address,uint256)"(
    offerId: PromiseOrValue<BigNumberish>,
    tokenBob: PromiseOrValue<string>,
    amountBob: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createOffer(
    offer: IMarsbaseBestBid.BBOfferParamsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "createOffer((address,uint256,address[],uint256,uint256))"(
    offer: IMarsbaseBestBid.BBOfferParamsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getActiveOffers(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "getActiveOffers()"(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "acceptBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelOffer(uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createBid(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "createBid(uint256,address,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createOffer(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "createOffer((address,uint256,address[],uint256,uint256))"(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getActiveOffers(
      overrides?: CallOverrides
    ): Promise<IMarsbaseBestBid.BBOfferStructOutput[]>;

    "getActiveOffers()"(
      overrides?: CallOverrides
    ): Promise<IMarsbaseBestBid.BBOfferStructOutput[]>;
  };

  filters: {
    "BidAccepted(uint256,address,uint256,uint256,uint256,uint256,tuple,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      aliceReceivedTotal?: null,
      aliceFeeTotal?: null,
      bobReceivedTotal?: null,
      bobFeeTotal?: null,
      offer?: null,
      bid?: null
    ): BidAcceptedEventFilter;
    BidAccepted(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      aliceReceivedTotal?: null,
      aliceFeeTotal?: null,
      bobReceivedTotal?: null,
      bobFeeTotal?: null,
      offer?: null,
      bid?: null
    ): BidAcceptedEventFilter;

    "BidCancelled(uint256,address,address,uint8,uint256,bytes32,tuple)"(
      offerId?: PromiseOrValue<BigNumberish> | null,
      bobAddress?: PromiseOrValue<string> | null,
      tokenBob?: PromiseOrValue<string> | null,
      reason?: null,
      bidIdx?: null,
      bidId?: null,
      bid?: null
    ): BidCancelledEventFilter;
    BidCancelled(
      offerId?: PromiseOrValue<BigNumberish> | null,
      bobAddress?: PromiseOrValue<string> | null,
      tokenBob?: PromiseOrValue<string> | null,
      reason?: null,
      bidIdx?: null,
      bidId?: null,
      bid?: null
    ): BidCancelledEventFilter;

    "BidCreated(uint256,address,address,uint256,bytes32,tuple)"(
      offerId?: PromiseOrValue<BigNumberish> | null,
      bobAddress?: PromiseOrValue<string> | null,
      tokenBob?: PromiseOrValue<string> | null,
      bidIdx?: null,
      bidId?: null,
      bid?: null
    ): BidCreatedEventFilter;
    BidCreated(
      offerId?: PromiseOrValue<BigNumberish> | null,
      bobAddress?: PromiseOrValue<string> | null,
      tokenBob?: PromiseOrValue<string> | null,
      bidIdx?: null,
      bidId?: null,
      bid?: null
    ): BidCreatedEventFilter;

    "OfferClosed(uint256,address,uint8,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      reason?: PromiseOrValue<BigNumberish> | null,
      offer?: null
    ): OfferClosedEventFilter;
    OfferClosed(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      reason?: PromiseOrValue<BigNumberish> | null,
      offer?: null
    ): OfferClosedEventFilter;

    "OfferCreated(uint256,address,address,tuple)"(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      tokenAlice?: PromiseOrValue<string> | null,
      params?: null
    ): OfferCreatedEventFilter;
    OfferCreated(
      id?: PromiseOrValue<BigNumberish> | null,
      aliceAddress?: PromiseOrValue<string> | null,
      tokenAlice?: PromiseOrValue<string> | null,
      params?: null
    ): OfferCreatedEventFilter;
  };

  estimateGas: {
    acceptBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "acceptBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "cancelBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "cancelOffer(uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createBid(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "createBid(uint256,address,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createOffer(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "createOffer((address,uint256,address[],uint256,uint256))"(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getActiveOffers(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "getActiveOffers()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "acceptBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelBid(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "cancelBid(uint256,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      bidIdx: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "cancelOffer(uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createBid(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "createBid(uint256,address,uint256)"(
      offerId: PromiseOrValue<BigNumberish>,
      tokenBob: PromiseOrValue<string>,
      amountBob: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createOffer(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "createOffer((address,uint256,address[],uint256,uint256))"(
      offer: IMarsbaseBestBid.BBOfferParamsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getActiveOffers(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "getActiveOffers()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
