/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MarsBase,
  MarsBaseInterface,
} from "../../../contracts/obsolete/MarsBase";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "minimumMet",
            type: "bool",
          },
          {
            internalType: "enum MarsBaseCommon.OfferType",
            name: "offerType",
            type: "MarsBaseCommon.OfferType",
          },
          {
            internalType: "uint256",
            name: "offerId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRemaining",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "offerer",
            type: "address",
          },
          {
            internalType: "address",
            name: "payoutAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenAlice",
            type: "address",
          },
          {
            internalType: "bool[3]",
            name: "capabilities",
            type: "bool[3]",
          },
          {
            internalType: "uint256[]",
            name: "amountBob",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsAlice",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsBob",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderAddresses",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderTokens",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "tokenBob",
            type: "address[]",
          },
        ],
        internalType: "struct MarsBaseCommon.MBOffer",
        name: "offer",
        type: "tuple",
      },
      {
        internalType: "address[]",
        name: "tokenBob",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amountBob",
        type: "uint256[]",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "cancelEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "modifyEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "holdTokens",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
        ],
        internalType: "struct MarsBaseCommon.OfferParams",
        name: "offerParameters",
        type: "tuple",
      },
    ],
    name: "changeOfferParams",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "minimumMet",
            type: "bool",
          },
          {
            internalType: "enum MarsBaseCommon.OfferType",
            name: "offerType",
            type: "MarsBaseCommon.OfferType",
          },
          {
            internalType: "uint256",
            name: "offerId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRemaining",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "offerer",
            type: "address",
          },
          {
            internalType: "address",
            name: "payoutAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenAlice",
            type: "address",
          },
          {
            internalType: "bool[3]",
            name: "capabilities",
            type: "bool[3]",
          },
          {
            internalType: "uint256[]",
            name: "amountBob",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsAlice",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsBob",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderAddresses",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderTokens",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "tokenBob",
            type: "address[]",
          },
        ],
        internalType: "struct MarsBaseCommon.MBOffer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum MarsBaseCommon.OfferType",
        name: "offerType",
        type: "MarsBaseCommon.OfferType",
      },
    ],
    name: "contractType",
    outputs: [
      {
        internalType: "enum MarsBaseCommon.ContractType",
        name: "",
        type: "MarsBaseCommon.ContractType",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountAlice",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "cancelEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "modifyEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "holdTokens",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
        ],
        internalType: "struct MarsBaseCommon.OfferParams",
        name: "offerParameters",
        type: "tuple",
      },
    ],
    name: "getOfferType",
    outputs: [
      {
        internalType: "enum MarsBaseCommon.OfferType",
        name: "",
        type: "MarsBaseCommon.OfferType",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nextOfferId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenAlice",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "tokenBob",
        type: "address[]",
      },
      {
        internalType: "uint256",
        name: "amountAlice",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "amountBob",
        type: "uint256[]",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "cancelEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "modifyEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "holdTokens",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
        ],
        internalType: "struct MarsBaseCommon.OfferParams",
        name: "offerParameters",
        type: "tuple",
      },
    ],
    name: "initOffer",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "minimumMet",
            type: "bool",
          },
          {
            internalType: "enum MarsBaseCommon.OfferType",
            name: "offerType",
            type: "MarsBaseCommon.OfferType",
          },
          {
            internalType: "uint256",
            name: "offerId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRemaining",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "offerer",
            type: "address",
          },
          {
            internalType: "address",
            name: "payoutAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenAlice",
            type: "address",
          },
          {
            internalType: "bool[3]",
            name: "capabilities",
            type: "bool[3]",
          },
          {
            internalType: "uint256[]",
            name: "amountBob",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsAlice",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsBob",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderAddresses",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderTokens",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "tokenBob",
            type: "address[]",
          },
        ],
        internalType: "struct MarsBaseCommon.MBOffer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountAlice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "offerAmountAlice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "offerAmountBob",
        type: "uint256",
      },
    ],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "minimumMet",
            type: "bool",
          },
          {
            internalType: "enum MarsBaseCommon.OfferType",
            name: "offerType",
            type: "MarsBaseCommon.OfferType",
          },
          {
            internalType: "uint256",
            name: "offerId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRemaining",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "offerer",
            type: "address",
          },
          {
            internalType: "address",
            name: "payoutAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenAlice",
            type: "address",
          },
          {
            internalType: "bool[3]",
            name: "capabilities",
            type: "bool[3]",
          },
          {
            internalType: "uint256[]",
            name: "amountBob",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsAlice",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsBob",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderAddresses",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderTokens",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "tokenBob",
            type: "address[]",
          },
        ],
        internalType: "struct MarsBaseCommon.MBOffer",
        name: "offer",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "cancelEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "modifyEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "holdTokens",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
        ],
        internalType: "struct MarsBaseCommon.OfferParams",
        name: "offerParams",
        type: "tuple",
      },
    ],
    name: "setOfferProperties",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "minimumMet",
            type: "bool",
          },
          {
            internalType: "enum MarsBaseCommon.OfferType",
            name: "offerType",
            type: "MarsBaseCommon.OfferType",
          },
          {
            internalType: "uint256",
            name: "offerId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeAlice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeBob",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "smallestChunkSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumSize",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountRemaining",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "offerer",
            type: "address",
          },
          {
            internalType: "address",
            name: "payoutAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenAlice",
            type: "address",
          },
          {
            internalType: "bool[3]",
            name: "capabilities",
            type: "bool[3]",
          },
          {
            internalType: "uint256[]",
            name: "amountBob",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsAlice",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "minimumOrderAmountsBob",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderAddresses",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "minimumOrderTokens",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "tokenBob",
            type: "address[]",
          },
        ],
        internalType: "struct MarsBaseCommon.MBOffer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MarsBase__factory {
  static readonly abi = _abi;
  static createInterface(): MarsBaseInterface {
    return new utils.Interface(_abi) as MarsBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarsBase {
    return new Contract(address, _abi, signerOrProvider) as MarsBase;
  }
}
