name: Build latest contract
on: 
  push:
    branches:
      - master
      - main

env:
  MB_GITHUB_TOKEN: ${{ secrets.MB_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependencies
        run: yarn
        
      - name: Prepare hardhat build
        run: yarn init-secret
        
      - name: Build project
        run: yarn build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Commit & push types
        uses: EndBug/add-and-commit@v8
        with:
          add: 'types'
          message: '[auto] types updated'
          github_token: ${{ env.MB_GITHUB_TOKEN }}


      - name: Get git commit SHA
        id: git-commit-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      
      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          git_tag_prefix: "v"
          github_token: ${{ env.MB_GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ steps.git-commit-sha.outputs.sha }}
